services:
  app_dopi:
    build: .
    env_file:
      - .env.dopi
    ports:
      - '4201:4200'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./quiz.db:/data/quiz.db:rw

  app_team:
    build: .
    env_file:
      - .env.team
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./quiz.db:/data/quiz.db:rw
