services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '4200:4200'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
