services:
  app:
    build: .
    env_file:
      - .env.prod
    ports:
      - '4200:4200'
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env.prod
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  game:
    image: naidonov/game
    ports:
      - "8000:80"

volumes:
  pg_data:

networks:
  quiz_network:
